version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[DEPENDENCY]"
      prefix-development: "[DEPENDENCY-DEV]"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[DEPENDENCY]"
      prefix-development: "[DEPENDENCY-DEV]"
